name: Deploy Pages

on:
  push:
    branches:
      - main  # Pas aan naar jouw default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Stap 1: Haal de code op
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Vergelijkbaar met GIT_SUBMODULE_STRATEGY: recursive

      # Stap 2: Installeer Python en afhankelijkheden
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          cd mdocotion && python setup.py install && cd ..

      # Stap 3: Build de site
      - name: Build site with MkDocs
        run: mkdocs build --site-dir public

      # Stap 4: Deploy naar GitHub Pages met een alternatieve actie
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.0.0
        with:
          branch: gh-pages  # De branch waar de site wordt gedeployed
          folder: ./public  # De map waarin je site is gegenereerd
          token: ${{ secrets.GITHUB_TOKEN }}  # Gebruik de GitHub token om te deployen

